<?php return
[
    'Bagerhat' => [
        'Bagerhat sadar',
        'Chitalmari',
        'Fakirhat',
        'Kachua upazila',
        'Mollahat',
        'Mongla',
        'Morrelganj',
        'Rampal',
        'Sarankhola',
        'test thana'
    ],
    'Bandarban' => [
        'Ali Kadam',
        'Bandarban sadar',
        'Lama',
        'Naikhongchari',
        'Rowangchhari',
        'Ruma',
        'Thanchi'
    ],
    'Barguna' => [
        'Amtali',
        'Bamna',
        'Barguna sadar',
        'Betagi',
        'Patharghata',
        'Taltali'
    ],
    'Barishal' => [
        'Agalijhara',
        'Babuganj',
        'Bakerganj',
        'Banaripara',
        'Barishal Sadar',
        'Gouronadi',
        'Hizla',
        'Mehendiganj',
        'Muladi',
        'Wazirpur'
    ],
    'Bhola' => [
        'Bhola Sadar',
        'Borhanuddin',
        'Char fasson',
        'Daulatkhan',
        'Lalmohan',
        'Manpura',
        'Tazumuddin'
    ],
    'Bogra' => [
        'Alamdighi',
        'Baropur (Bogura)',
        'Bogura Sadar',
        'Dhunat',
        'Dhupchancia',
        'Gabtoli',
        'Kahaloo',
        'Nandigram',
        'Saraikandi',
        'Shajahanpur',
        'Sherpur',
        'Shibganj',
        'Sonatola'
    ],
    'Brahmanbaria' => [
        'Akhaura',
        'Ashuganj',
        'Bancharampur',
        'Bijoynagar',
        'Brahmanbaria Sadar',
        'Kasba',
        'Kautoli',
        'Nabinagar',
        'Nasrinagar',
        'Sarail'
    ],
    'Chandpur' => [
        'Chandpur Sadar',
        'Dhakirgaon',
        'Faridganj',
        'Haimchar',
        'Hajiganj',
        'Kachua',
        'Matlab North',
        'Motlab dokkhin',
        'Shahrasti'
    ],
    'Chapainawabganj' => [
        'Bholahat',
        'Chapainawabganj Sadar',
        'Gomastapur',
        'Nachole',
        'Shibganj Sadar'
    ],
    'Chittagong' => [
        'Akbar Shah',
        'Anwara',
        'Bakolia',
        'Bandar - CTG',
        'Banskhali',
        'Bayazid Bostami',
        'Bhujpur',
        'Boalkhali',
        'CEPZ',
        'Chandanaish',
        'Chandgaon',
        'Chawk Bazar',
        'Chittagong Sadar',
        'Doublemooring',
        'Fatikchori',
        'Halishahar',
        'Hathazari',
        'Karnaphuli',
        'Keranihat',
        'Khulshi',
        'Kotwali - CTG',
        'Lohagara',
        'Mirsharai',
        'Pahartali',
        'Panchlaish',
        'Patenga',
        'Patiya',
        'Rangunia',
        'Raozan',
        'Sadarghat - CTG',
        'Sandwip',
        'Satkania',
        'shantirhat(patiya)',
        'Shantirhat(Patiya)-CTG',
        'Sitakunda',
        'Sitakunda  (Citygate)',
        'Zorarganj'
    ],
    'Chuadanga' => [
        'Alamdanga',
        'Chuandanga Sadar',
        'Damurhuda',
        'Darshana',
        'Jibannagar'
    ],
    'Cox\'s Bazar' => [
        'Chakaria',
        'Cox\'s Bazar Sadar',
        'Eidgaon',
        'Kutubdia',
        'Moheskhali',
        'Pekua',
        'Ramu',
        'Teknaf',
        'Ukhiya'
    ],
    'Cumilla' => [
        'Bangora-Bazar',
        'Barura',
        'Brahmanpara',
        'Burichang',
        'Chandina',
        'Chauddagram',
        'Comilla Sadar South Model',
        'Daudkandi',
        'Debidwar',
        'Homna',
        'Kandirpar',
        'Kotwali Model',
        'Laksam',
        'Lalmai',
        'Meghna',
        'Monoharganj',
        'Muradnagar',
        'Nangalkot',
        'Titas'
    ],
    'Dhaka City' => [
        'Adabor',
        'Airport',
        'Ati Bazar (keraniganj)',
        'Azompur',
        'Badda',
        'Banani',
        'Bangshal',
        'Bashundhara R/A',
        'Bhashantek',
        'Cantonment',
        'Chalkbazar',
        'Dakshin khan',
        'Darus Salam',
        'Demra',
        'Dhanmondi',
        'Gandaria',
        'Gulistan',
        'Gulshan',
        'Hatirjheel',
        'Hazaribag',
        'Jattrabari',
        'Kadamtali',
        'Kafrul',
        'Kalabagan',
        'Kamrangirchar',
        'Khilgaon',
        'Khilkhet',
        'Kotwali',
        'Lalbagh',
        'Mirpur',
        'Mohammadpur',
        'Motijheel',
        'Mugda',
        'New Market',
        'Pallabi',
        'Paltan',
        'Panthapath',
        'Purbachal',
        'Ramna',
        'Rampura',
        'Rupnagar',
        'Sabujbag',
        'Shah Ali',
        'Shah Ali Market',
        'Shahbag',
        'Shahjahanpur',
        'Sher-e-Bangla Nagar',
        'Shyampur',
        'Sutrapur',
        'Tejgaon',
        'Tejgaon Industrial Area',
        'Turag',
        'Uttara',
        'Uttarkhan',
        'Vasantek',
        'Vatara',
        'Wari',
        'Zone Not Clear'
    ],
    'Dhaka Sub-Urban' => [
        'Ashulia',
        'Dhamrai',
        'Dohar',
        'Hemayetpur',
        'Keraniganj Model',
        'Nawabganj',
        'Savar',
        'South keraniganj'
    ],
    'Dinajpur' => [
        'Biral',
        'Birampur',
        'Birganj',
        'Bochaganj',
        'Chirirbandar',
        'Dinajpur Sadar',
        'Fulbari',
        'Ghoraghat',
        'Hakimpur',
        'Kaharole',
        'Khansama',
        'Nawabganj Upazila',
        'Parbatipur'
    ],
    'Faridpur' => [
        'Alfadanga',
        'Bhanga',
        'Boalmari',
        'Charbhadrasan',
        'Faridpur Sadar',
        'Madhukhali',
        'Nagarkanda',
        'Sadarpur',
        'Shaltha'
    ],
    'Feni' => [
        'Chagalnaiya',
        'Dagunbhuiyan',
        'Feni sadar',
        'Fulgazi',
        'Mohipal',
        'Parshuram',
        'Sonagazi'
    ],
    'Gaibandha' => [
        'Fulchari',
        'Gabindaganj',
        'Gaibandha Sadar',
        'Palashbari',
        'Sadullapur',
        'Saghata',
        'Sundarganj'
    ],
    'Gazipur' => [
        'Gazipur Sadar',
        'Kaliakair',
        'Kaliakhair Upazila',
        'Kaliganj upazila',
        'Kapasia',
        'Kashimpur',
        'Rajendrapur',
        'Sreepur',
        'Tongi'
    ],
    'Gopalganj' => [
        'Boultali',
        'Gopalganj Sadar',
        'Kasiani',
        'Kotalipara',
        'Muksudpur',
        'tungipara'
    ],
    'Habiganj' => [
        'Ajmiriganj',
        'Bahubal',
        'Baniachong',
        'Chunarughat',
        'Habiganj Sadar',
        'Lakhai',
        'Madhobpur',
        'Nabiganj',
        'Shayestaganj'
    ],
    'Jamalpur' => [
        'Baksiganj',
        'Dewanganj',
        'Islampur',
        'Jamalpur Sadar',
        'Madarganj',
        'Melandaha',
        'Nandina',
        'Sarishabari'
    ],
    'Jashore' => [
        'Abhaynagar',
        'Bagharpara',
        'Chaugacha',
        'Jashore Sadar',
        'Jhikorgacha',
        'keshobpur',
        'Manirampur',
        'Sharsha'
    ],
    'Jhalokati' => [
        'Jhalokati sadar',
        'Kathalia',
        'Nalchity',
        'Rajapur'
    ],
    'Jhenaidah' => [
        'Harinakunda',
        'Jhenaidah Sadar',
        'Kaliganj',
        'Kotchandpur',
        'Maheshpur',
        'Shailkupa'
    ],
    'Joypurhat' => [
        'Akkelpur',
        'Joypurhat Sadar',
        'Kalai',
        'Khetlal',
        'Panchbibi'
    ],
    'Khagrachari' => [
        'Dighinala',
        'Guimara',
        'khagrachari sadar',
        'Laxmichari',
        'Mahalahari',
        'Manikchari',
        'Matiranga',
        'Panchari',
        'Ramgarh'
    ],
    'Khulna' => [
        'Batiaghata',
        'Circuit House',
        'Dacope',
        'Daulatpur (Khulna)',
        'Dighalia',
        'Dumuria',
        'Gollamari (Khulna)',
        'Khulna Sadar',
        'Koyra',
        'Paikgacha',
        'Phultala',
        'Rupsha',
        'Terokhada'
    ],
    'Kishoreganj' => [
        'Austagram',
        'Bajitpur',
        'Bhairab',
        'Hossainpur',
        'Itna',
        'Karimganj',
        'Katiadi',
        'Kishoreganj Sadar',
        'Kuliarchar',
        'Mithamain',
        'Nikli',
        'Pakundia',
        'Tarail'
    ],
    'Kurigram' => [
        'Bhurungamari',
        'Char Rajibpur',
        'Chilmari',
        'fulbari',
        'kurigram sadar',
        'Nageshwari',
        'Phulbari',
        'Rajarhat',
        'Raomari',
        'Ulipur'
    ],
    'Kustia' => [
        'Bheramara',
        'Daulatpur',
        'Khoksa',
        'Kumarkhali',
        'Kushtia Sadar',
        'Mirpur upazila'
    ],
    'Lalmonirhat' => [
        'Aditmari',
        'Hatibandha',
        'Kaliganj sadar',
        'Lalmonirhat Sadar',
        'Patgram'
    ],
    'Laxmipur' => [
        'Chandraganj',
        'Kamalnagar',
        'Laxmipur Sadar',
        'Raipur',
        'Ramganj',
        'Ramgati'
    ],
    'Madaripur' => [
        'Dasar',
        'Kalkini',
        'Madaripur sadar',
        'Rajoir',
        'Shibchar'
    ],
    'Magura' => [
        'Magura sadar',
        'Mohammadpur upazila',
        'Shalikha',
        'Sreepur upazila'
    ],
    'Manikganj' => [
        'Daulatpur upazila',
        'Ghior',
        'Harirampur',
        'Manikganj Sadar',
        'Saturia',
        'Shivalaya',
        'Singair'
    ],
    'Meherpur' => [
        'Gangni',
        'Meherpur sadar',
        'Mujibnagar'
    ],
    'Moulvibazar' => [
        'Barlekha',
        'Barlekha (Moulvibazar)',
        'Juri',
        'Kamolgani',
        'Kulaura',
        'Moulvibazar Sadar',
        'Rajnagar',
        'Rajnagor',
        'Sherpur Moulvibazar',
        'Sreemangal'
    ],
    'Munshiganj' => [
        'Gazaria',
        'Louhajang',
        'Munshiganj Sadar',
        'Sirajdikhan',
        'Sreenagar',
        'Tongibari'
    ],
    'Mymensingh' => [
        'Bhaluka',
        'Dhobaura',
        'Fulbaria',
        'Gafargaon',
        'Gouripur',
        'Haluaghat',
        'Ishwarganj',
        'Muktagacha',
        'Mymensingh Sadar',
        'Nandail',
        'Pagla',
        'Phulpur',
        'Shambhuganj',
        'Tarakanda',
        'Trishal'
    ],
    'Naogaon' => [
        'Atrai',
        'Badolgachi',
        'Dharmoirhat',
        'Manda',
        'Mohadevpur',
        'Naogaon sadar',
        'Niamatpur',
        'Patnitala',
        'Porsha',
        'Raninagar',
        'Sapahar'
    ],
    'Narail' => [
        'Kalia',
        'Lohagara',
        'Naragati',
        'Narali Sadar'
    ],
    'Narayanganj' => [
        'Araihajar',
        'Bandar',
        'Fatullah',
        'Kanchpur Highway',
        'Narayanganj Sadar',
        'Rupganj',
        'Shiddhirganj',
        'Sonargaon'
    ],
    'Narshindi' => [
        'Belabo',
        'Ghorashal',
        'Madhobdi',
        'Manohardi',
        'monohardi',
        'Narshindi sadar',
        'Narsingdi Sadar',
        'Palash',
        'Raipura',
        'Shibpur'
    ],
    'Natore' => [
        'Bagatipara',
        'Baraigram',
        'Gopalpur Pourosova',
        'Gurudaspur',
        'Lalpur',
        'Naldanga',
        'Natore Sadar',
        'Singra'
    ],
    'Netrokona' => [
        'Atpara',
        'Barhatta',
        'Durgapur',
        'Kalmakanda',
        'Kendua',
        'Khaliajuri',
        'Madan',
        'Mohonganj',
        'Netrokona Sadar',
        'Parbadhala'
    ],
    'Nilphamari' => [
        'Dimla',
        'Domar',
        'jaldhaka',
        'kishoreganj',
        'Nilphamari Sadar',
        'Saidpur'
    ],
    'Noakhali' => [
        'Begamganj',
        'Chatkhil',
        'Companyganj',
        'Hatiya',
        'Kabir Hat',
        'Noakhali Sadar',
        'Senbagh',
        'Sonaimuri',
        'Subarnachar'
    ],
    'Pabna' => [
        'Ataikula (Pabna)',
        'Atgharia',
        'Bera',
        'Bhangura',
        'Chatmohar',
        'Ishwardi',
        'Pabna Sadar',
        'Santhia',
        'Sujanagar'
    ],
    'Panchgarh' => [
        'Atwari',
        'Boda',
        'Debiganj',
        'Panchgarh sadar Thana',
        'Tetulia'
    ],
    'Patuakhali' => [
        'Bauphal',
        'Dashmina',
        'Dumki',
        'Galachipa',
        'Kalapara',
        'Mirzaganj',
        'Patuakhali Sadar',
        'Rangabali'
    ],
    'Pirojpur' => [
        'Bhandaria',
        'Indurkani',
        'Kawkhali',
        'Mathbaria',
        'Nazirpur',
        'Nesarabad',
        'Pirojpur Sadar',
        'Swarupkati'
    ],
    'Rajbari' => [
        '(Goalanda Mor) Rajbari Office',
        'Baliakandi',
        'Goalananda',
        'Kalukhali',
        'pangsha',
        'Rajbari Sadar'
    ],
    'Rajshahi' => [
        'Airport (Rajshahi)',
        'Bagha',
        'Bagmara',
        'Belpukur',
        'Boalia',
        'Chandrima Thana',
        'Charghat',
        'Damkura',
        'Durgapur',
        'Godagari',
        'Kashiadanga',
        'Katakhali',
        'Kornohar',
        'Matihar Thana',
        'Mohanpur',
        'Paba',
        'Puthia',
        'Rajpara',
        'Rajshahi Sadar',
        'Shah Makdam',
        'Tanore'
    ],
    'Rangamati' => [
        'Bagaichhari',
        'Barkal',
        'Belaichhari',
        'Juraichhari',
        'Kaptai',
        'Kawkhali upazila',
        'Langadu',
        'Naniarchar',
        'Rajasthali',
        'Rangamati Sadar'
    ],
    'Rangpur' => [
        'Badarganj',
        'Gangachara',
        'Kaunia',
        'Khulahati',
        'Mitapukur',
        'Pirgacha',
        'Pirganj',
        'Rangpur Sadar',
        'Shatibari',
        'Taraganj'
    ],
    'Shariatpur' => [
        'Bhedarganj',
        'Damudya',
        'Gosairhat',
        'Naria',
        'Sakhipur upazila',
        'Shariatpur sadar',
        'Zajira'
    ],
    'Shatkhira' => [
        'Assasuni',
        'Debhata',
        'Kalaroa',
        'Kaliganj',
        'Patkelghata',
        'Shatkhira sadar',
        'Shyamnagar',
        'Tala'
    ],
    'Sherpur' => [
        'Jhenaigati',
        'Nakla',
        'Nalitabari',
        'Sherpur sadar',
        'Sreebardi'
    ],
    'Sirajganj' => [
        'Belkuchi',
        'Chowhali',
        'Kamarkhanda',
        'Kazipur',
        'Raiganj',
        'Shahjadpur',
        'Sirajganj Sadar',
        'Tarash',
        'Ullapara'
    ],
    'Sunamganj' => [
        'Bishwamvapur',
        'chhatak',
        'Derai',
        'Dharmapasha',
        'Dowarabazar',
        'Jagannathpur',
        'Jamalganj',
        'Moddonagar',
        'Shantiganj',
        'Sullah',
        'Sunamganj Sadar',
        'Tahirpur'
    ],
    'Sylhet' => [
        'Balaganj',
        'Beanibazar',
        'Bishanath',
        'Companyganj upazila',
        'Fenchuganj',
        'gobindaganj',
        'Golapganj',
        'Gowainghat',
        'Jalalabad',
        'Jalalabad cantonment',
        'Jintiapur',
        'Kanaighat',
        'Osmaninagar',
        'Shahporan',
        'South Surma',
        'Sylhet sadar',
        'Zakiganj'
    ],
    'Tangail' => [
        'Basail',
        'Bhuapur',
        'Delduar',
        'Dhanbari',
        'Ghatail',
        'Gopalpur',
        'Kalihati',
        'Madhupur',
        'Mirzapur',
        'Nagarpur',
        'Sakhipur',
        'Sokhipur',
        'Tangali Sadar'
    ],
    'Thakurgaon' => [
        'Baliadangi',
        'Haripur',
        'Pirganj upazila',
        'Ranisankail',
        'Thakurgaon Sadar'
    ]
];
